### PR TITLE
Bring Utils into installer to enable intelligent installer update

### PR DESCRIPTION
**Pull request by PoeppingT**
----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by brtrvn — CHANGES_REQUESTED** [review]
We can replace `SaaSBoostInstall::generatePassword` with `Utils::randomString(16)`

Can use `Utils::isBlank` in `getExistingSaaSBoostEnvironment`

Optionally, we could also update the S3 artifacts bucket naming to use `randomString(12, "[^a-z0-9]")` for the suffix to match what CloudFormation would have done instead of what we're currently doing with UUID.

**Comment by PoeppingT** [comment]
> We can replace `SaaSBoostInstall::generatePassword` with `Utils::randomString(16)`

Our Cognito UserPool password policy currently requires at least one lowercase letter, uppercase letter, and number. `Utils::randomString` does not guarantee this in the same way that `SaaSBoostInstall::generatePassword` does. I will alter `SaaSBoostInstall::generatePassword` to conform to that policy while still using `Utils::randomString`.

**Review by brtrvn — COMMENTED** [review]
Looks good. In the future, we can look at adding required character type constraints to the Utils randomString method.

**Review by brtrvn — APPROVED** [review]
Looks good

**Pull request merged**
