### PR TITLE
Update to getting-started.md, fix for #15

### PR DESCRIPTION
**Pull request by hariohmprasath**
Updated description to the default instance type available in the drop down

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by brtrvn** [comment]
Can you also please make the same change to the User Guide?

**Comment by hariohmprasath** [comment]
> Can you also please make the same change to the User Guide?

Sure thing. I have updated those as well. Let me know if any other changes are requried

**Comment by brtrvn** [comment]
Have you updated your pull request? I only see the changes to getting-started.md.

**Comment by hariohmprasath** [comment]
> Have you updated your pull request? I only see the changes to getting-started.md.

Done

**Comment by brtrvn** [comment]
Looks good. Merged.

**Pull request merged**
