### PR TITLE
Standardize tables in the UI to conform to one style.

### PR DESCRIPTION
**Pull request by PoeppingT**
This commit changes all tables in the admin UI to:
1. contain ID, Created, and Modified fields. Id is first, Created and Modified are second to last and last, respectively
2. all have no striped rows, rows that change color when you hover over them, and be responsive to input size
3. all have clickable rows, which take you to the represented record
4. all be sorted by Modified date ascending by default.

This commit also removes the unused MetricList components and changes the link to the Tenant page on the Onboarding view page to be an actual link with normal blue color and underline using the `<a>` tag.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by brtrvn — CHANGES_REQUESTED** [review]
Looks good with the exception of inconsistent date time formatting throughout the UI.

System Users List and Detail
Full month in UTC with AM/PM and TZ

Tiers List and Detail
Full month in UTC with AM/PM no TZ

Tenants List and Detail
Full month in local time with AM/PM no TZ

Onboarding List
Full month in local time with AM/PM no TZ

Onboarding Detail
Created full month, with full day of week, in local time with AM/PM no TZ
Modified full month, with full day of week, in local time with seconds with am/pm lowercase no TZ

I suggest we go with the formatting that the tenants list and detail display. That is `MMMM d, yyyy h:mm a` or `March 1, 2023 5:00 PM`

**Review by brtrvn — COMMENTED** [review]
System User details screen is showing the time zone abbreviation. Everything else looks consistent.

**Comment by PoeppingT** [comment]
> System User details screen is showing the time zone abbreviation. Everything else looks consistent.

Nice catch, fixed

**Review by brtrvn — APPROVED** [review]
Looks good

**Pull request merged**
