### PR TITLE
Fix for #42 & #50

### PR DESCRIPTION
**Pull request by hariohmprasath**
**Code changes includes:**

#42 - Code changes to pass in requested CPU units, so the check can take into account required + existing to see if it exceeds the quota
#50 - Fix to provide required IAM policy `rds:CreateDBClusterSnapshot` for RDS deletion

----
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by hariohmprasath** [comment]
Hi @brtrvn,
I have removed the additional dependencies that got added in the last commit. Feel free to review it and let me know, if any changes are required.

Thanks

**Comment by brtrvn** [comment]
Can we please split these PRs up into the different issues they are solving?
Let's have a single PR for the Node version problem and a different PR for the virtual CPU quota issue.
Please double-check code formatting so it follows the existing format (curly brackets after if statements, spaces between assignment operators (=), 4 space indents, etc).

**Comment by hariohmprasath** [comment]
> Can we please split these PRs up into the different issues they are solving?
> Let's have a single PR for the Node version problem and a different PR for the virtual CPU quota issue.
> Please double-check code formatting so it follows the existing format (curly brackets after if statements, spaces between assignment operators (=), 4 space indents, etc).

Hi @brtrvn, Thanks for the review comments. I have created two pull requests as you suggested and taken care of the `if` condition formatting.

**Comment by hariohmprasath** [comment]
Hi @brtrvn and @4patelr,
Can this PR be reviewed and merged? Thanks

**Comment by brtrvn** [comment]
Hari - thank you for the initial bug report on vCPU limits #42 
After reviewing this issue and your proposed changes, we believe the best direction is to refactor and improve the quota checking functionality that happens as a pre-flight to tenant onboarding. We are going to close this PR, but be on the lookout for some new work around the quota stuff and we will be sure to resolve the vCPU bug at the same time. Looking forward to you contributing to the improved functionality.

**Pull request closed without merging**
